/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.CardLayout;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import DTO.ThongKeSach;
import DTO.ThongKeDG;
import java.util.HashMap;
import java.util.Map;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minh
 */
//testcommit
public class BaoCaoThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form BaoCaoThongKePanel
     */
    
    public BaoCaoThongKePanel() {
        initComponents();
        pnBarChart.setVisible(true);
        this.pnBarChart.setEnabled(false);
        lamMoi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbLoaiThongKe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBTraCuu = new javax.swing.JButton();
        cbThang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTraCuu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnBarChart = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1074, 571));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 250));

        jLabel1.setText("Loại Thống Kê");

        cbLoaiThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê tình trạng mượn sách theo tháng", "Thống kê tiền phạt của độc giả theo tháng" }));
        cbLoaiThongKe.setSelectedIndex(-1);
        cbLoaiThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiThongKeActionPerformed(evt);
            }
        });

        jLabel2.setText("Chọn năm");

        jLabel4.setText("Chọn tháng");

        jBTraCuu.setText("Tra cứu");
        jBTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTraCuuActionPerformed(evt);
            }
        });

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbThang.setSelectedIndex(-1);

        tbTraCuu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbTraCuu.setEnabled(false);
        jScrollPane1.setViewportView(tbTraCuu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbThang, javax.swing.GroupLayout.Alignment.LEADING, 0, 111, Short.MAX_VALUE)
                            .addComponent(txtNam, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(25, 25, 25)
                        .addComponent(jBTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbLoaiThongKe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLoaiThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbThang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(205, 245, 253));

        jLabel3.setBackground(new java.awt.Color(205, 245, 253));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(12, 53, 106));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BÁO CÁO THỐNG KÊ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 255), null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnBarChart.setBackground(new java.awt.Color(255, 255, 255));
        pnBarChart.setMaximumSize(new java.awt.Dimension(587, 382));
        pnBarChart.setMinimumSize(new java.awt.Dimension(587, 382));

        javax.swing.GroupLayout pnBarChartLayout = new javax.swing.GroupLayout(pnBarChart);
        pnBarChart.setLayout(pnBarChartLayout);
        pnBarChartLayout.setHorizontalGroup(
            pnBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnBarChartLayout.setVerticalGroup(
            pnBarChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean kiemTraThongTin(){
        if(this.cbLoaiThongKe.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn loại thống kê","Thông báo",1);
        }
        else if(this.cbThang.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập tháng","Thông báo",1);
        }
        else if("".equals(this.txtNam.getText())){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập năm","Thông báo",1);
        }
        else if(!isNumeric(this.txtNam.getText())){
            JOptionPane.showMessageDialog(null, "Năm phải là số","Thông báo",1);
        }
        else return true;
        return false;
    }
     private boolean isNumeric(String str) {
        return str.matches("\\d+");
    }
    public void lamMoi(){
       
        this.txtNam.setText("");
        this.cbThang.setSelectedIndex(-1);
        this.cbLoaiThongKe.setSelectedIndex(-1);
        DefaultTableModel model = (DefaultTableModel) tbTraCuu.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        
    }
    public void setDataToChart0(Map<Integer,Integer> ds){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Map.Entry<Integer, Integer> entry : ds.entrySet()) {
            dataset.addValue(entry.getValue(), "SOLUOTMUON", String.valueOf(entry.getKey()));
        }

        JFreeChart barChart = ChartFactory.createBarChart( 
                "Thống kê mượn sách",
                "Mã đầu sách","Số lượt mượn"
                , dataset, PlotOrientation.VERTICAL, false, true, false);
        this.pnBarChart.removeAll();
        this.pnBarChart.setLayout(new CardLayout());
        this.pnBarChart.add(new ChartPanel(barChart));
        this.pnBarChart.validate();
    }
    public void setDataToChart1(Map<Integer,Integer> ds){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Map.Entry<Integer, Integer> entry : ds.entrySet()) {
            dataset.addValue(entry.getValue(), "TONGTIENPHAT", String.valueOf(entry.getKey()));
        }

        JFreeChart barChart = ChartFactory.createBarChart( 
                "Thống kê tiền phạt",
                "Mã độc giả","Tổng tiền phạt"
                , dataset, PlotOrientation.VERTICAL, false, true, false);
        this.pnBarChart.removeAll();
        this.pnBarChart.setLayout(new CardLayout());
        this.pnBarChart.add(new ChartPanel(barChart));
        this.pnBarChart.validate();
    }
    private void jBTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTraCuuActionPerformed
        // TODO add your handling code here:
        if(kiemTraThongTin()){
            int thang=this.cbThang.getSelectedIndex()+1;
            int nam=Integer.parseInt(this.txtNam.getText());
            DefaultTableModel model = (DefaultTableModel) tbTraCuu.getModel();
            String[] rowData;
            String[] columnData;
            Map<Integer,Integer> ds=new HashMap<>();
            if(this.cbLoaiThongKe.getSelectedIndex()==0){
                lamMoi();
                columnData=new String[] {"Mã đầu sách","Tên đầu sách","Số lượt mượn"};
                for(String columnName:columnData){
                    model.addColumn(columnName);
                }
                Vector<ThongKeSach> list=DAO.ThongKeDAO.getListThongKeSach(thang, nam);
                for (ThongKeSach tks:list){
                    int maDauSach=tks.getMaDS();
                    String tenDauSach=tks.getTenDS();
                    int soLuotMuon=tks.getSoLuotMuon();
                    rowData =new String[] {String.valueOf(maDauSach),tenDauSach,String.valueOf(soLuotMuon)};
                    model.addRow(rowData);
                    ds.put(maDauSach, soLuotMuon);
                    setDataToChart0(ds);
                }
            }
            else {
                lamMoi();
                columnData=new String[] {"Mã độc giả","Tên độc giả","Tổng số lượng sách mượn","Tổng tiền phạt"};
                for(String columnName:columnData){
                    model.addColumn(columnName);
                }
                Vector<ThongKeDG> list=DAO.ThongKeDAO.getListThongKeDG(thang, nam);
                for(ThongKeDG tkdg:list){
                    int maDocGia=tkdg.getMaDocGia();
                    String tenDocGia=tkdg.getTenDocGia();
                    int tongSlSachMuon=tkdg.getTongSlSachMuon();
                    int tongTienPhat=tkdg.getTongTienPhat();
                    rowData = new String[]{String.valueOf(maDocGia),tenDocGia,String.valueOf(tongSlSachMuon),String.valueOf(tongTienPhat)};      
                    model.addRow(rowData);
                    ds.put(maDocGia, tongTienPhat);
                    setDataToChart1(ds);
                }
            }
            
                  
        }
        
    }//GEN-LAST:event_jBTraCuuActionPerformed

    private void cbLoaiThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoaiThongKeActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLoaiThongKe;
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JButton jBTraCuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnBarChart;
    private javax.swing.JTable tbTraCuu;
    private javax.swing.JTextField txtNam;
    // End of variables declaration//GEN-END:variables

    
}
