package GUI;

import DTO.HoaDon;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author NguyenNguyen
 */
public class QuanLyHoaDonPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyHoaDonPanel
     */
    public QuanLyHoaDonPanel() {
        initComponents();
        this.txtTienThu.setEnabled(true);
        this.txtTienNoConLai.setEnabled(false);
        this.txtTongTienNo.setEnabled(false);
        this.tbHoaDon.setVisible(true);
        lamMoi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTongTienNo = new javax.swing.JTextField();
        txtTienThu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTienNoConLai = new javax.swing.JTextField();
        cbMaDocGia = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btThemMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã độc giả", "Tiền thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonMouseClicked(evt);
            }
        });
        tbHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbHoaDonKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDon);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, null));

        jLabel6.setText("Tiền thu");

        txtTienThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThuActionPerformed(evt);
            }
        });

        jLabel4.setText("Tổng tiền nợ");

        jLabel5.setText("Mã độc giả");

        jLabel8.setText("Tiền nợ còn lại");

        cbMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaDocGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienThu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbMaDocGia, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTienNoConLai)
                    .addComponent(txtTongTienNo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cbMaDocGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienNo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienNoConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(250, 50));

        btThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-50.png"))); // NOI18N
        btThemMoi.setFocusable(false);
        btThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(btThemMoi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void lamMoi(){
        this.txtTienThu.setText("");
        this.txtTienNoConLai.setText("");
        this.txtTongTienNo.setText("");
        this.cbMaDocGia.removeAllItems();
        this.cbMaDocGia.setSelectedIndex(-1);
        Vector<Integer> listMaDocGia=DAO.HoaDonDAO.getlistMaDocGia();
        for(int i=0;i<listMaDocGia.size();i++){
            this.cbMaDocGia.addItem(String.valueOf(listMaDocGia.get(i)));
        }
        DefaultTableModel model = (DefaultTableModel) tbHoaDon.getModel();
        Vector<HoaDon> listHoaDon=DAO.HoaDonDAO.getlistHOADON();
        for (HoaDon hd:listHoaDon){
            int maHoaDon=hd.getMaHoaDon();
            int maDocGia=hd.getMaDocGia();
            int tienThu=hd.getTienThu();
            String[] rowData = {String.valueOf(maHoaDon), String.valueOf(maDocGia),String.valueOf(tienThu)};
            model.addRow(rowData);
        }
        
    }
    private void tbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHoaDonMouseClicked

    private void tbHoaDonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbHoaDonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHoaDonKeyPressed

    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        // TODO add your handling code here:
       if(kiemTraDieuKien()){
            int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thêm hóa đơn này", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                HoaDon hd=new HoaDon();
                hd.setMaDocGia(Integer.parseInt(this.cbMaDocGia.getSelectedItem().toString()));
                hd.setTienThu(Integer.parseInt(this.txtTienThu.getText()));
                DAO.HoaDonDAO.ThemHoaDon(hd);           
                lamMoi();
            }
       }
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void cbMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaDocGiaActionPerformed
        if(this.cbMaDocGia.getSelectedIndex()!=-1){
            int maDocGia=Integer.parseInt(this.cbMaDocGia.getSelectedItem().toString());
            this.txtTongTienNo.setText(String.valueOf(DAO.HoaDonDAO.getTongTienNo(maDocGia)));
        }
    }//GEN-LAST:event_cbMaDocGiaActionPerformed
    private boolean isNumeric(String str) {
        return str.matches("\\d+");
    }
    private boolean kiemTraDieuKien(){
        if(this.cbMaDocGia.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên độc giả", "Thông báo", 1);
            
        }
        else if(this.txtTienThu.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tiền thu","Thông báo",1);
        }
        else if(!isNumeric(this.txtTienThu.getText())){
            JOptionPane.showMessageDialog(null, "Tiền thu không hợp lệ","Thông báo",1);
            
        }
        else if(Integer.parseInt(this.txtTienThu.getText())>Integer.parseInt(this.txtTongTienNo.getText())){
            JOptionPane.showMessageDialog(null, "Tiền thu lớn hơn tiền nợ","Thông báo",1);
        }
        else return true ;
        return false;
    }
    private void txtTienThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThuActionPerformed
        if(kiemTraDieuKien()){
            int tienThu=Integer.parseInt(this.txtTienThu.getText());
            int tongTienNo=Integer.parseInt(this.txtTongTienNo.getText());
            int conLai=tongTienNo-tienThu;
            this.txtTienNoConLai.setText(String.valueOf(conLai));
        }
    }//GEN-LAST:event_txtTienThuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThemMoi;
    private javax.swing.JComboBox<String> cbMaDocGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JTextField txtTienNoConLai;
    private javax.swing.JTextField txtTienThu;
    private javax.swing.JTextField txtTongTienNo;
    // End of variables declaration//GEN-END:variables
}
