/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**ss
 *
 * @author minh
 */
import DTO.DocGia;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import DAO.*;
import DTO.DauSach;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
//testcommit
public class QuanLyTheDocGiaPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyDocGia
     */
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
   
    public QuanLyTheDocGiaPanel() {
        initComponents();
        setBackground(Color.white);
        lamMoi();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LTlb = new javax.swing.JLabel();
        txtMaDocGia = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jDateNgaySinh = new com.toedter.calendar.JDateChooser();
        DHLb = new javax.swing.JLabel();
        btnGiaHan = new javax.swing.JButton();
        txtNgayLapThe = new javax.swing.JTextField();
        txtNgayDenHan = new javax.swing.JTextField();
        rdbtSinhVien = new javax.swing.JRadioButton();
        rdbtGiangVien = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDocGia = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btThemMoi = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(205, 245, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(309, 395));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ngày sinh");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Loại độc giả");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Địa chỉ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Email");

        LTlb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LTlb.setText("Ngày lập thẻ");

        txtMaDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaDocGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaDocGiaKeyPressed(evt);
            }
        });

        DHLb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DHLb.setText("Ngày đến hạn");

        btnGiaHan.setBackground(new java.awt.Color(12, 53, 106));
        btnGiaHan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGiaHan.setForeground(new java.awt.Color(255, 255, 255));
        btnGiaHan.setText("Gia hạn độc giả");
        btnGiaHan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGiaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaHanActionPerformed(evt);
            }
        });

        txtNgayLapThe.setEditable(false);

        txtNgayDenHan.setEditable(false);

        rdbtSinhVien.setBackground(new java.awt.Color(205, 245, 253));
        btnGroup.add(rdbtSinhVien);
        rdbtSinhVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbtSinhVien.setText("sinh viên");
        rdbtSinhVien.setToolTipText("");

        rdbtGiangVien.setBackground(new java.awt.Color(205, 245, 253));
        btnGroup.add(rdbtGiangVien);
        rdbtGiangVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbtGiangVien.setText("giảng viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnGiaHan)
                        .addGap(136, 136, 136))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(DHLb, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LTlb, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail)
                                    .addComponent(txtNgayLapThe)
                                    .addComponent(txtNgayDenHan)
                                    .addComponent(txtDiaChi)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(rdbtSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbtGiangVien)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtHoTen)
                                    .addComponent(jDateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtSinhVien)
                    .addComponent(rdbtGiangVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LTlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayLapThe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayDenHan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DHLb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(205, 245, 253));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 53, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ THẺ ĐỘC GIẢ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        tbDocGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã độc giả", "Họ tên", "Ngày sinh", "Loại độc giả", "Địa chỉ", "Email", "Ngày lập thẻ", "Ngày đến hạn", "Số tiền nợ"
            }
        ));
        tbDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDocGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDocGia);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(250, 50));

        btThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-50.png"))); // NOI18N
        btThemMoi.setFocusable(false);
        btThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(btThemMoi);

        btCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-edit-50.png"))); // NOI18N
        btCapNhat.setFocusable(false);
        btCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });
        jToolBar1.add(btCapNhat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDocGiaMouseClicked
        // TODO add your handling code here:                                                  
        int selectedRow = this.tbDocGia.getSelectedRow();
        if(selectedRow!=-1) {
            DefaultTableModel model = (DefaultTableModel) this.tbDocGia.getModel();
            this.txtMaDocGia.setText(String.valueOf(model.getValueAt(selectedRow, 0)));
            this.txtHoTen.setText(String.valueOf(model.getValueAt(selectedRow, 1)));
            try {
                this.jDateNgaySinh.setDate(formatter.parse(String.valueOf(model.getValueAt(selectedRow, 2))));
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyTheDocGiaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            if("Sinh viên".equals(String.valueOf(model.getValueAt(selectedRow, 3)))){
                this.rdbtSinhVien.setSelected(true);
            }
            else {
                this.rdbtGiangVien.setSelected(true);
            }
            this.txtDiaChi.setText(String.valueOf(model.getValueAt(selectedRow, 4)));
            this.txtEmail.setText(String.valueOf(model.getValueAt(selectedRow, 5)));
            this.txtNgayLapThe.setText(String.valueOf(model.getValueAt(selectedRow, 6)));
            this.txtNgayDenHan.setText(String.valueOf(model.getValueAt(selectedRow, 7)));
            if(DAO.DocGiaDAO.KTHanThe(Integer.parseInt(this.txtMaDocGia.getText()))){
                this.btnGiaHan.setVisible(true);
            }    
            else {
                this.btnGiaHan.setVisible(false);
            }
        }
    }//GEN-LAST:event_tbDocGiaMouseClicked
    public final void lamMoi() {
        DefaultTableModel model = (DefaultTableModel) this.tbDocGia.getModel();
        model.setRowCount(0);
        Vector<DocGia> listDocGia=DAO.DocGiaDAO.getListDocGia();
        for (DocGia ds:listDocGia){
            model.addRow(new Object[] {ds.getMaDocGia(),ds.getHoTen(),
            ds.getNgaySinh(),((ds.getLoaiDocGia()==0)?"Sinh viên":"Giảng viên"),
            ds.getDiaChi(),ds.getEmail(),ds.getNgayLapThe(),ds.getNgayDenHan(),ds.getTienNo()});
        }
        txtMaDocGia.setText("");
        txtHoTen.setText("");
        jDateNgaySinh.setDate(null);
        txtDiaChi.setText("");
        rdbtSinhVien.setSelected(true);
        txtEmail.setText("");

        // Lấy ngày hiện tại
        Date ngayHienTai = new Date();
        txtNgayLapThe.setText(formatter.format(ngayHienTai));
        
        // Cộng 4 tháng cho ngày lập thẻ
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(ngayHienTai);
        calendar.add(Calendar.MONTH, 4);

        // Gán giá trị ngày đến hạn
        Date ngayDenHan = calendar.getTime();
        txtNgayDenHan.setText(formatter.format(ngayDenHan));

        btnGiaHan.setVisible(false);
    }
    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        // TODO add your handling code here:
        try {
            if (this.tbDocGia.getSelectedColumn()== -1){
                JOptionPane.showMessageDialog(null, "Bạn cần chọn độc giả để sửa", "Thông báo", 1);
            }
            else if (kiemTraThongTin()) {
                int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn cập nhật độc giả này", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    int mdg=Integer.parseInt(this.txtMaDocGia.getText());
                    DocGia dg = new DocGia();
                    dg.setHoTen(txtHoTen.getText());
                    
                    dg.setNgaySinh(new java.sql.Date(jDateNgaySinh.getDate().getTime()));
                    if(rdbtSinhVien.isSelected())
                    {
                        dg.setLoaiDocGia(0);
                    }
                    else dg.setLoaiDocGia(1);
                    dg.setDiaChi(txtDiaChi.getText());
                    dg.setEmail(txtEmail.getText());
                    DAO.DocGiaDAO.SuaDocGia(dg, mdg);
                    lamMoi();
                }
            }
        } 
        catch (ParseException ex) {
            Logger.getLogger(QuanLyTheDocGiaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
     
            
    }//GEN-LAST:event_btCapNhatActionPerformed
    private Boolean kiemTraThongTin() throws ParseException{
        if (this.txtHoTen.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên độc giả", "Thông báo", 1);
        }
        else if (this.txtDiaChi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ", "Thông báo", 1);
        }
        else if (this.txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập email", "Thông báo", 1);
        }
        else if (this.jDateNgaySinh.getDate() == null){
            JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ", "Thông báo", 1);
        }
        else if (DAO.DocGiaDAO.KTNgaySinh(new java.sql.Date(jDateNgaySinh.getDate().getTime()), new java.sql.Date(new Date().getTime()))==false){
            JOptionPane.showMessageDialog(null, "Ngày sinh phải nhỏ hơn ngày lập thẻ!", "Thông báo", 1);
        }
        else return true; 
        return false;
    }

    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed

        try {
            if (kiemTraThongTin()){
                int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thêm độc giả này", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    //Gọi hàm xử lý phía dưới
                    DocGia dg = new DocGia();
                    dg.setHoTen(txtHoTen.getText());
                    dg.setNgaySinh(new java.sql.Date(jDateNgaySinh.getDate().getTime()));
                    if(rdbtSinhVien.isSelected())
                    {
                        dg.setLoaiDocGia(0);
                    }
                    else dg.setLoaiDocGia(1);
                    dg.setDiaChi(txtDiaChi.getText());
                    dg.setEmail(txtEmail.getText());
                    dg.setNgayLapThe(new java.sql.Date(formatter.parse(this.txtNgayLapThe.getText()).getTime()));
                    dg.setNgayDenHan(new java.sql.Date(formatter.parse(this.txtNgayDenHan.getText()).getTime()));
                    DocGiaDAO.ThemDocGia(dg);
                    lamMoi();
                    
                }
                
            }
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyTheDocGiaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void txtMaDocGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDocGiaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtHoTen.requestFocus();
        }
    }//GEN-LAST:event_txtMaDocGiaKeyPressed

    private void btnGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaHanActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn gia hạn độc giả này", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            DAO.DocGiaDAO.GiaHanThe(Integer.parseInt(txtMaDocGia.getText()));
            JOptionPane.showMessageDialog(null, "Độc giả được gia hạn thành công", "Thông báo", 1);
            lamMoi();
        }
    }//GEN-LAST:event_btnGiaHanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DHLb;
    private javax.swing.JLabel LTlb;
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btThemMoi;
    private javax.swing.JButton btnGiaHan;
    private javax.swing.ButtonGroup btnGroup;
    private com.toedter.calendar.JDateChooser jDateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton rdbtGiangVien;
    private javax.swing.JRadioButton rdbtSinhVien;
    private javax.swing.JTable tbDocGia;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtNgayDenHan;
    private javax.swing.JTextField txtNgayLapThe;
    // End of variables declaration//GEN-END:variables
}
