/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import DTO.DauSach;
import java.awt.Color;
import javax.swing.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class QuanLyDauSachPanel extends javax.swing.JPanel    {

    /**
     * Creates new form QuanLyDauSachPanel
     */
    public QuanLyDauSachPanel(){
        initComponents();
        this.txtSanCo.setEnabled(false);
        this.txtDangChoMuon.setEnabled(false);
        setBackground(Color.white);
        lamMoi();
    }
    public void lamMoi(){
        DefaultTableModel model = (DefaultTableModel) this.tbDauSach.getModel();
        model.setRowCount(0);
        Vector<DauSach> listDauSach=DAO.DauSachDAO.getListDauSach();
        for (DauSach ds:listDauSach){
            model.addRow(new Object[] {ds.getMaDauSach(),ds.getTenDauSach(),
                ds.getTacGia(),ds.getNXB(),ds.getNamXB(),
                ds.getTongSo(),ds.getViTri(),
                ds.getSanCo(),ds.getDangChoMuon()
            });
        }
        this.txtTenDauSach.setText("");
        this.txtTacGia.setText("");
        this.txtNXB.setText("");
        this.txtNamXB.setText("");
        this.txtTongSo.setText("");
        this.txtViTri.setText("");
        this.txtSanCo.setVisible(false);
        this.txtDangChoMuon.setVisible(false);
        this.labelSanCo.setVisible(false);
        this.labelDCM.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btThemMoi = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelSanCo = new javax.swing.JLabel();
        labelDCM = new javax.swing.JLabel();
        txtTenDauSach = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        txtTongSo = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        txtSanCo = new javax.swing.JTextField();
        txtDangChoMuon = new javax.swing.JTextField();
        txtNamXB = new javax.swing.JTextField();
        txtMaDauSach = new javax.swing.JTextField();
        txtSanCocu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDauSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1074, 571));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(250, 50));

        btThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-50.png"))); // NOI18N
        btThemMoi.setFocusable(false);
        btThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(btThemMoi);

        btCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-edit-50.png"))); // NOI18N
        btCapNhat.setFocusable(false);
        btCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });
        jToolBar1.add(btCapNhat);

        jPanel1.setBackground(new java.awt.Color(205, 245, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, null));
        jPanel1.setPreferredSize(new java.awt.Dimension(309, 394));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tên đầu sách");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tác giả");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nhà XB");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Năm XB");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tổng số");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Vị trí");

        labelSanCo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSanCo.setText("Sẵn có");

        labelDCM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDCM.setText("Đang cho mượn");

        txtSanCo.setEditable(false);
        txtSanCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSanCoActionPerformed(evt);
            }
        });

        txtDangChoMuon.setEditable(false);

        txtNamXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamXBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSanCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDCM, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTacGia)
                    .addComponent(txtNXB)
                    .addComponent(txtTongSo)
                    .addComponent(txtViTri)
                    .addComponent(txtSanCo)
                    .addComponent(txtDangChoMuon)
                    .addComponent(txtNamXB)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaDauSach, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtSanCocu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTenDauSach, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenDauSach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTacGia)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSanCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSanCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDangChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDCM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSanCocu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDauSach, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jScrollPane1.setWheelScrollingEnabled(false);

        tbDauSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbDauSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đầu sách", "Tên đầu sách", "Tác giả", "Nhà XB", "Năm XB", "Tổng số", "Vị trí", "Sẵn có", "Đang cho mượn"
            }
        ));
        tbDauSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDauSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDauSach);

        jPanel2.setBackground(new java.awt.Color(205, 245, 253));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 53, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐẦU SÁCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbDauSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDauSachMouseClicked
        // TODO add your handling code here:
        int selectedRow=this.tbDauSach.getSelectedRow();
        if(selectedRow!=-1) {
            DefaultTableModel model = (DefaultTableModel) this.tbDauSach.getModel();
            this.txtMaDauSach.setText(String.valueOf(model.getValueAt(selectedRow, 0)));
            this.txtTenDauSach.setText(String.valueOf(model.getValueAt(selectedRow, 1)));
            this.txtTacGia.setText(String.valueOf(model.getValueAt(selectedRow, 2)));
            this.txtNXB.setText(String.valueOf(model.getValueAt(selectedRow, 3)));
            this.txtNamXB.setText(String.valueOf(model.getValueAt(selectedRow, 4)));
            this.txtTongSo.setText(String.valueOf(model.getValueAt(selectedRow, 5)));
            this.txtViTri.setText(String.valueOf(String.valueOf(model.getValueAt(selectedRow, 6))));
            this.txtSanCo.setText(String.valueOf(String.valueOf(model.getValueAt(selectedRow, 7))));
            this.txtDangChoMuon.setText(String.valueOf(String.valueOf(String.valueOf(model.getValueAt(selectedRow, 8)))));
            this.txtSanCo.setVisible(true);
            this.txtDangChoMuon.setVisible(true);
            this.labelSanCo.setVisible(true);
            this.labelDCM.setVisible(true);
        }
        
    }//GEN-LAST:event_tbDauSachMouseClicked
    boolean kiemTraThongTin(){
        if (this.txtTenDauSach.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên đầu sách","Thông báo",1);
        }
        else if (this.txtTacGia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập tên tác giả","Thông báo",1);
        }
        else if(this.txtNXB.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập tên nhà xuất bản","Thông báo",1);
        }
        else if(this.txtNamXB.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập năm sản xuất","Thông báo",1);
        }
        else if(this.txtTongSo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập tổng số","Thông báo",1);
        }
        else if(this.txtViTri.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập vị trí","Thông báo",1);
        }
        else if(!isNumeric(this.txtNamXB.getText())){
                JOptionPane.showMessageDialog(null, "Năm sản xuất phải là số","Thông báo",1);
        }
        else if(!isNumeric(this.txtTongSo.getText())){
                JOptionPane.showMessageDialog(null, "Tổng số phải là số","Thông báo",1);
        }
        else if (!DAO.DauSachDAO.KTNamXB(Integer.parseInt(this.txtNamXB.getText()))){
            JOptionPane.showMessageDialog(null, "Năm xuất bản phải bé hơn năm hiện tại","Thông báo",1);
        }
        else if (!DAO.DauSachDAO.KTTongSoThem(Integer.parseInt(this.txtTongSo.getText()))){
            JOptionPane.showMessageDialog(null, "Tổng số phải lớn hơn 0","Thông báo",1);
        }
        else return true ;
        return false;
    }
    private boolean isNumeric(String str) {
        return str.matches("\\d+");
    }
    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        // TODO add your handling code here:
        if (kiemTraThongTin()){
            int result = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thêm cuốn sách này", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DauSach ds=new DauSach();
                ds.setTenDauSach(this.txtTenDauSach.getText());
                ds.setTacGia(this.txtTacGia.getText());
                ds.setNXB(this.txtNXB.getText());
                ds.setNamXB(Integer.parseInt(this.txtNamXB.getText()));
                ds.setTongSo(Integer.parseInt(this.txtTongSo.getText()));
                ds.setViTri(this.txtViTri.getText());
                ds.setSanCo(Integer.parseInt(this.txtTongSo.getText()));
                ds.setDangChoMuon(0);
                DAO.DauSachDAO.ThemDauSach(ds);
                lamMoi();
            }
        }
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
       if (this.tbDauSach.getSelectedColumn()==-1){
           JOptionPane.showMessageDialog(null, "Bạn cần chọn cuốn sách để sửa","Thông báo",1);
       } 
       else if (kiemTraThongTin()){
           int result=JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa cuốn sách này","Xác nhận",JOptionPane.YES_NO_OPTION);
           if(result==JOptionPane.YES_OPTION){
               
               if(DAO.DauSachDAO.KTTongSoSua(Integer.parseInt(this.txtMaDauSach.getText()),Integer.parseInt(this.txtTongSo.getText()))){
                    DauSach ds=new DauSach();
                    ds.setTenDauSach(this.txtTenDauSach.getText());
                    ds.setTacGia(this.txtTacGia.getText());
                    ds.setNXB(this.txtNXB.getText());
                    ds.setNamXB(Integer.parseInt(this.txtNamXB.getText()));
                    ds.setTongSo(Integer.parseInt(this.txtTongSo.getText()));
                    ds.setViTri(this.txtViTri.getText());
                    ds.setSanCo(Integer.parseInt(this.txtTongSo.getText())-Integer.parseInt(this.txtDangChoMuon.getText()));
                    ds.setDangChoMuon(Integer.parseInt(this.txtDangChoMuon.getText()));
                    DAO.DauSachDAO.SuaDauSach(ds, Integer.parseInt(this.txtMaDauSach.getText()));
                    lamMoi();
               }
               else {
                    JOptionPane.showMessageDialog(null, "Tổng số sửa phải lớn hơn tổng số ban đầu","Thông báo",1);
                    
               }
           }
       }
       
        
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void txtNamXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamXBActionPerformed

    private void txtSanCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSanCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSanCoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btThemMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelDCM;
    private javax.swing.JLabel labelSanCo;
    private javax.swing.JTable tbDauSach;
    private javax.swing.JTextField txtDangChoMuon;
    private javax.swing.JTextField txtMaDauSach;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtSanCo;
    private javax.swing.JTextField txtSanCocu;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenDauSach;
    private javax.swing.JTextField txtTongSo;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
