/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author minh
 */
import DTO.PhieuTraSach;
import DTO.ChiTietTraSach;
import java.awt.Color;
import javax.swing.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class QuanLyPhieuTraSachPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhieuTraSachPanel
     */
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy ");
    public QuanLyPhieuTraSachPanel() {
        initComponents();
        setBackground(Color.white);    
        lamMoi();
        txtMaDocGia.setEnabled(false);
        txtTenDocGia.setEnabled(false);
        txtNgayTra.setEnabled(false);
        this.tbCTTS.setEnabled(false);
    }
    public void lamMoi(){
        Vector<Integer> listMaPhieuMuonSach=DAO.PhieuTraSachDAO.getListMaPhieuMuonSach();
        this.cbMaPhieuMuonSach.removeAllItems();
        this.txtMaDocGia.setText("");
        this.txtTenDocGia.setText("");
        txtNgayTra.setText(formatter.format(new Date()));
        for(int i=0;i<listMaPhieuMuonSach.size();i++){
            this.cbMaPhieuMuonSach.addItem(String.valueOf(listMaPhieuMuonSach.get(i)));
        }
        DefaultTableModel model = (DefaultTableModel) this.tbPhieuTraSach.getModel();
        model.setRowCount(0);
        Vector<PhieuTraSach> listPTS=DAO.PhieuTraSachDAO.getListPhieuTraSach();
        for (PhieuTraSach pts:listPTS){
            model.addRow(new Object[]{pts.getMaPhieuTra(),pts.getMaPhieuMuon(),pts.getNgayTra(),pts.getSoNgayTraTre(),pts.getTienPhatKiNay()});          
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tbMaSach1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btThemMoi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelMaPhieuMuon = new javax.swing.JLabel();
        lbMaDG = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCTTS = new javax.swing.JTable();
        txtNgayTra = new javax.swing.JTextField();
        txtTenDocGia = new javax.swing.JTextField();
        lbTenDocGia = new javax.swing.JLabel();
        cbMaPhieuMuonSach = new javax.swing.JComboBox<>();
        txtMaDocGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhieuTraSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        tbMaSach1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MASACH", "TENDAUSACH"
            }
        ));
        jScrollPane3.setViewportView(tbMaSach1);

        jLabel7.setText("jLabel7");

        setPreferredSize(new java.awt.Dimension(1074, 571));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-50.png"))); // NOI18N
        btThemMoi.setFocusable(false);
        btThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemMoi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });
        jToolBar1.add(btThemMoi);

        jPanel1.setBackground(new java.awt.Color(205, 245, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, null));
        jPanel1.setPreferredSize(new java.awt.Dimension(309, 394));

        labelMaPhieuMuon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelMaPhieuMuon.setText("Mã phiếu mượn sách");

        lbMaDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaDG.setText("Mã độc giả");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ngày trả");

        tbCTTS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbCTTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đầu sách", "Tên đầu sách", "Tiền phạt"
            }
        ));
        jScrollPane2.setViewportView(tbCTTS);

        txtNgayTra.setEditable(false);

        lbTenDocGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTenDocGia.setText("Tên độc giả");

        cbMaPhieuMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaPhieuMuonSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMaPhieuMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaDG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTenDocGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayTra)
                            .addComponent(cbMaPhieuMuonSach, 0, 208, Short.MAX_VALUE)
                            .addComponent(txtMaDocGia)
                            .addComponent(txtTenDocGia))))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMaPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMaPhieuMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMaDG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbPhieuTraSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbPhieuTraSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu trả", "Mã phiếu mượn sách", "Ngày trả", "Số ngày trả trễ", "Tiền phạt kì này"
            }
        ));
        tbPhieuTraSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhieuTraSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPhieuTraSach);

        jPanel2.setBackground(new java.awt.Color(205, 245, 253));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(12, 53, 106));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ PHIẾU TRẢ SÁCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 204), null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        // TODO add your handling code here:
        if(this.cbMaPhieuMuonSach.getSelectedIndex()!=-1){
            int result=JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm phiếu trả sách không","Xác nhận",JOptionPane.YES_NO_OPTION);
            if(result==JOptionPane.YES_OPTION){
                PhieuTraSach pts=new PhieuTraSach();
                pts.setMaPhieuMuon(Integer.parseInt(this.cbMaPhieuMuonSach.getSelectedItem().toString()));
                try {
                    pts.setNgayTra(new java.sql.Date(formatter.parse(this.txtNgayTra.getText()).getTime()));
                } catch (ParseException ex) {
                    Logger.getLogger(QuanLyPhieuTraSachPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                DAO.PhieuTraSachDAO.InsertPhieuTraSach(pts);
                Vector<ChiTietTraSach> listCTTS=DAO.PhieuTraSachDAO.getCTTS(pts.getMaPhieuMuon());
                DefaultTableModel model = (DefaultTableModel) tbCTTS.getModel();
                for (ChiTietTraSach ctts:listCTTS){
                    
                    int maDauSach=ctts.getMaDauSach();
                    String tenDauSach=DAO.PhieuTraSachDAO.getTenDauSach(maDauSach);
                    int tienPhat=ctts.getTienPhat();
                    Object[] rowData = {maDauSach, tenDauSach, tienPhat};
                    model.addRow(new Object[]{maDauSach, tenDauSach, tienPhat});
                }
                lamMoi();
            }
        }
        else {
             JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã phiếu trả sách","Thông báo",1);
        }
            
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void tbPhieuTraSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhieuTraSachMouseClicked

    }//GEN-LAST:event_tbPhieuTraSachMouseClicked

    private void cbMaPhieuMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaPhieuMuonSachActionPerformed
        
        int selectedIndex = this.cbMaPhieuMuonSach.getSelectedIndex();
        if (selectedIndex!=-1){
                int maPhieuMuonSach=Integer.parseInt(this.cbMaPhieuMuonSach.getItemAt(selectedIndex));
                int maDocGia=DAO.PhieuTraSachDAO.getMaDocGia(maPhieuMuonSach);
                String tenDocGia=DAO.PhieuTraSachDAO.getTenDocGia(maDocGia);
                this.txtMaDocGia.setText(String.valueOf(maDocGia));
                this.txtTenDocGia.setText(tenDocGia);
            }
        
        
    }//GEN-LAST:event_cbMaPhieuMuonSachActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThemMoi;
    private javax.swing.JComboBox<String> cbMaPhieuMuonSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelMaPhieuMuon;
    private javax.swing.JLabel lbMaDG;
    private javax.swing.JLabel lbTenDocGia;
    private javax.swing.JTable tbCTTS;
    private javax.swing.JTable tbMaSach1;
    private javax.swing.JTable tbPhieuTraSach;
    private javax.swing.JTextField txtMaDocGia;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTenDocGia;
    // End of variables declaration//GEN-END:variables
}
